name: ci/cd

on:
  push:
    branches: [ master ]

jobs:
  slack-on-fail:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./.github/workflows/slack-notify.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_TEXT: ":steam_locomotive: new commit in <https://github.com/juliaogris/lego|juliaogris/lego> \n ${{ github.event.head_commit.message }} \n ${{ github.sha }}"
